name: CI CI/CD
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

env:
  CI: false
  env_master: ${{ secrets.ENV_MASTER }}

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: import env file
        run: |
          touch ./.env && echo "$env_master" >> ./.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: build && push 
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: geesunandan/sample-node:master